pipeline {
  agent any
  tools {nodejs "Node"}

   stages {
      stage('NPM Setup') {
      steps {
         sh '''
         cd mountain-traveler/front-end
         rm -rf android
         rm -rf node_modules
         npm install
         '''
      }
   }
   stage('Cordova install') {
   steps {
      sh 'npm install -g @ionic/cli --force'
     }
   }
//    stage('IOS Build') {
//    steps {
//       sh 'ionic cordova build ios --release'
//      }
//   }

   stage('Android Build') {
   steps {
      sh '''
      cd mountain-traveler/front-end
      ionic build
      ls -a
      ionic capacitor add android
      ionic capacitor build android --release
      '''
   }
  }

   stage('APK Sign') {
   steps {
      sh 'jarsigner -storepass password -keystore ./mt-release-key.keystore platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk mountainTraveler'
   }
  }

   stage('Publish iOS') {
      steps {
       echo "Publish iOS Action"
    }
   }

   stage('Publish Android') {
     steps {
    echo "Publish Android API Action"
   }
  }

 }
}


//
// ls -a
// cd mountain-traveler/front-end
// npm install
// npm run build
