pipeline {
  agent any
  tools {nodejs "node"}

   stages {
      stage('Git') {
        steps {
          git 'https://github.com/skuracj/mountains-traveler'
        }
      }
      stage('NPM Setup') {
      steps {
         sh 'npm install'
      }
   }
   stage('Cordova install') {
   steps {
      sh 'npm install -g ionic cordova'
     }
   }
   stage('IOS Build') {
   steps {
      sh 'ionic cordova build ios --release'
     }
  }

   stage('Android Build') {
   steps {
      sh 'ionic cordova build android --release'
   }
  }

   stage('APK Sign') {
   steps {
      sh 'jarsigner -storepass password -keystore ./mt-release-key.keystore platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk mountainTraveler'
   }
  }

   stage('Publish iOS') {
      steps {
       echo "Publish iOS Action"
    }
   }

   stage('Publish Android') {
     steps {
    echo "Publish Android API Action"
   }
  }

 }
}

