plugins:
  - serverless-offline

service: mt-backend
app: mountain-traveler
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: 'arn:aws:dynamodb:eu-west-1:*:*'

functions:
  profileGet:
    handler: profile/get.main
    events:
      - http:
          path: profile
          method: get
  profileUpdate:
    handler: profile/update.main
    events:
      - http:
          path: profile
          method: patch
  userGetById:
    handler: user/get.main
    events:
      - http:
          path: user/{id}
          method: get
  usersGetByIds:
    handler: users/get.main
    events:
      - http:
          path: users/{ids}
          method: get
  usersGetMostActiveByIds:
    handler: users/get.mostActive
    events:
      - http:
          path: users/most-active/{ids}
          method: get
  storyGetByUserId:
    handler: stories/get.main
    events:
      - http:
          path: stories/user/{userId}
          method: get
  storyRemoveById:
    handler: stories/delete.main
    events:
      - http:
          path: stories/{id}
          method: delete
#          authorizer: userPools / ?
#  authorizerFunc:
#    handler: handler.authorizerFunc

resources:
  - ${file(resources/tables.yml)}

